name = "DL_CA"
uuid = "b96abbd3-39d5-40b8-86d9-05b9e5907d4b"
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
